# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: 
url: http://www.kotnikd.com/
title: Denis Kotnik
email: denis.kotnik@gmail.com
author: Denis Kotnik
description: > # "Spletna stran Denisa Kotnik"
exclude: ['README.md']

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope-o
    title: email
    url: mailto:denis.kotnik@gmail.com
  - icon: address-card-o
    title: cv
    url: /pdf/CV_Denis_Kotnik.pdf
  - icon: github
    title: github
    url: https://github.com/kotnikd3
  - icon: facebook-square
    title: facebook
    url: https://www.facebook.com/kotnikd3